# Generated by Django 4.2 on 2024-03-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_roles', 'Can view roles')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
