# Generated by Django 4.2 on 2023-11-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
