import "@mantine/core/styles.css";
import "@/styles/globals.css";

import type { AppProps } from "next/app";
import Head from "next/head";
import { MantineProvider, createTheme } from '@mantine/core';
import { QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Roboto_Flex as Roboto } from "next/font/google";
import { SnackbarProvider } from "notistack";

import { AuthProvider } from "@/components/auth/AuthProvider";
import defaultQueryClient from "@/api/clients/defaultQueryClient";

const roboto = Roboto({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

const theme = createTheme({
  fontFamily: roboto.style.fontFamily,
});

export default function App({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <title>App Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MantineProvider theme={theme}>
        <QueryClientProvider client={defaultQueryClient}>
          <AuthProvider defaultSetCallbackUrlParam={false}>
            <SnackbarProvider maxSnack={5} dense autoHideDuration={10000}>
              <div id="__app" className={roboto.className}>
                <Component {...pageProps} />
              </div>
            </SnackbarProvider>
            <ReactQueryDevtools initialIsOpen={false} />
          </AuthProvider>
        </QueryClientProvider>
      </MantineProvider>
    </>
  )
}
