# Generated by Django 4.2 on 2024-03-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='license_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(db_index=True, verbose_name='Dia registro')),
                ('register_datetime', models.DateTimeField(verbose_name='Fecha registro')),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.alerttype')),
                ('gx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.gx')),
            ],
        ),
    ]
