# Generated by Django 4.2 on 2024-02-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehistory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.gxstatus'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.gxstatus'),
        ),
        migrations.AddField(
            model_name='gxstatus',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.deployment'),
        ),
        migrations.AlterField(
            model_name='gxstatus',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
