# Generated by Django 4.2 on 2024-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alerttype_devicestatus_license_end_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestatus',
            name='license_end',
        ),
        migrations.AddField(
            model_name='device',
            name='license_end',
            field=models.DateTimeField(null=True),
        ),
    ]
