# Generated by Django 4.2 on 2024-03-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_devicehistory_status_devicestatus_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gxstatus',
            name='name',
        ),
    ]
