# Generated by Django 4.2 on 2024-03-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_gxstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gxstatus',
            name='reason',
            field=models.IntegerField(null=True, verbose_name='Razón'),
        ),
    ]
