# Generated by Django 4.2 on 2024-03-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_devicestatus_license_end_device_license_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='gxstatus',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
