# Generated by Django 4.2 on 2024-04-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_gxstatus_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttype',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
