# Generated by Django 4.2 on 2024-04-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_devicestatus_last_alert_unitstatus_last_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeverityCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('date', models.DateField(db_index=True)),
                ('severity_counts', models.JSONField()),
                ('status_fields', models.JSONField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.deployment')),
            ],
        ),
    ]
