# Generated by Django 4.2 on 2024-04-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_severitycount_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
