# Generated by Django 4.2 on 2024-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_unitstatus_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitstatus',
            name='last_alert',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
