# Generated by Django 4.2 on 2024-04-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_alter_unitstatus_last_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='severitycount',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.client'),
        ),
    ]
