# Generated by Django 4.2 on 2024-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_severitycount_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severitycount',
            name='status_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
