# Generated by Django 4.2 on 2024-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_alter_severitycount_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unithistory',
            name='on_trip',
            field=models.BooleanField(blank=True, null=True, verbose_name='On trip'),
        ),
        migrations.AlterField(
            model_name='unitstatus',
            name='on_trip',
            field=models.BooleanField(blank=True, null=True, verbose_name='On trip'),
        ),
    ]
