# Generated by Django 4.2 on 2024-04-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_alter_unithistory_on_trip_alter_unitstatus_on_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='keyname',
            field=models.CharField(null=True, verbose_name='Clave'),
        ),
    ]
