# Generated by Django 4.2 on 2024-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_client_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_password',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='api_username',
            field=models.CharField(null=True),
        ),
    ]
