# Generated by Django 4.2 on 2024-04-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_client_api_password_client_api_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='api_password',
            field=models.BinaryField(null=True),
        ),
    ]
