# Generated by Django 4.2 on 2024-05-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_server_severmetrics_serverstatus_serverhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='sever_id',
            new_name='server_id',
        ),
    ]
