# Generated by Django 4.2 on 2024-05-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_rename_sever_id_server_server_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeverMetrics',
            new_name='ServerMetrics',
        ),
    ]
