# Generated by Django 4.2 on 2024-05-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_rename_severmetrics_servermetrics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerMetrics',
            new_name='ServerMetric',
        ),
    ]
