# Generated by Django 4.2 on 2024-05-02 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_rename_servermetrics_servermetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverhistory',
            name='metric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.servermetric'),
        ),
    ]
