# Generated by Django 4.2 on 2024-05-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_alter_serverhistory_metric_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverhistory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.server'),
        ),
    ]
