# Generated by Django 4.2 on 2024-05-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_alter_serverhistory_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverhistory',
            options={'verbose_name_plural': 'Server histories'},
        ),
        migrations.AlterModelOptions(
            name='serverstatus',
            options={'verbose_name_plural': 'Server status'},
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_id',
            new_name='aws_id',
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='last_activity',
            field=models.DateTimeField(blank=True),
        ),
    ]
