# Generated by Django 4.2 on 2024-05-10 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0026_serverregion_server_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailDeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(null=True, verbose_name='Last update')),
                ('last_connection', models.DateTimeField(null=True, verbose_name='Last connection')),
                ('last_alert', models.DateTimeField(null=True)),
                ('delayed', models.BooleanField(null=True)),
                ('delay_time', models.DurationField(default=datetime.timedelta(0))),
                ('log_counts', models.JSONField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.device')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.gxstatus')),
            ],
        ),
        migrations.CreateModel(
            name='RetailDeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(db_index=True, verbose_name='Dia registro')),
                ('register_datetime', models.DateTimeField(verbose_name='Fecha registro')),
                ('last_connection', models.DateTimeField(null=True, verbose_name='Last connection')),
                ('last_alert', models.DateTimeField(null=True)),
                ('delayed', models.BooleanField(null=True)),
                ('delay_time', models.DurationField(default=datetime.timedelta(0))),
                ('log_counts', models.JSONField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.device')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.gxstatus')),
            ],
        ),
    ]
