# Generated by Django 4.2 on 2024-05-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_retaildevicestatus_retaildevicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retaildevicehistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.device'),
        ),
    ]
