# Generated by Django 4.2 on 2024-05-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_alter_retaildevicehistory_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retaildevicehistory',
            name='delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retaildevicehistory',
            name='last_alert',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retaildevicestatus',
            name='delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retaildevicestatus',
            name='last_alert',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
