# Generated by Django 4.2 on 2024-05-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0029_alter_retaildevicehistory_delayed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retaildevicehistory',
            options={'verbose_name_plural': 'Retail device histories'},
        ),
        migrations.AlterModelOptions(
            name='retaildevicestatus',
            options={'verbose_name_plural': 'Retail device status'},
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
