# Generated by Django 4.2 on 2024-05-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0030_alter_retaildevicehistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverstatus',
            name='active',
        ),
    ]
