# Generated by Django 4.2 on 2024-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0031_remove_serverstatus_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='retaildevicestatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
