# Generated by Django 4.2 on 2024-05-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0034_alter_gxstatus_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True)),
                ('end_datetime', models.DateTimeField(blank=True)),
                ('start_date', models.DateField(blank=True, db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True)),
                ('success', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.unit')),
            ],
        ),
    ]
