# Generated by Django 4.2 on 2024-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0035_unittrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittrip',
            name='connection',
            field=models.BooleanField(default=False),
        ),
    ]
