# Generated by Django 4.2 on 2024-05-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0037_alter_unittrip_end_date_alter_unittrip_end_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unittrip',
            old_name='connection',
            new_name='active',
        ),
    ]
