# Generated by Django 4.2 on 2024-05-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0038_rename_connection_unittrip_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instance_class', models.CharField(max_length=50)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.serverregion')),
            ],
        ),
        migrations.AddField(
            model_name='servermetric',
            name='service',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.CreateModel(
            name='RDSStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('last_activity', models.DateTimeField(blank=True)),
                ('activity_data', models.JSONField(blank=True, null=True)),
                ('rds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.rds')),
            ],
        ),
        migrations.CreateModel(
            name='RDSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_datetime', models.DateTimeField()),
                ('register_date', models.DateField(db_index=True)),
                ('state', models.CharField(max_length=50)),
                ('metric_value', models.FloatField()),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.servermetric')),
                ('rds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.server')),
            ],
        ),
    ]
