# Generated by Django 4.2 on 2024-05-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0039_rds_servermetric_service_rdsstatus_rdshistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdshistory',
            old_name='state',
            new_name='status',
        ),
    ]
