# Generated by Django 4.2 on 2024-05-22 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0040_rename_state_rdshistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdshistory',
            name='rds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.rds'),
        ),
    ]
