# Generated by Django 4.2 on 2024-05-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0041_alter_rdshistory_rds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdshistory',
            options={'verbose_name_plural': 'RDS histories'},
        ),
        migrations.AlterModelOptions(
            name='rdsstatus',
            options={'verbose_name_plural': 'RDS status'},
        ),
        migrations.AddField(
            model_name='server',
            name='client',
            field=models.ManyToManyField(to='monitor.client'),
        ),
    ]
