# Generated by Django 4.2 on 2024-05-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0042_alter_rdshistory_options_alter_rdsstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='client',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.rds')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.deployment')),
                ('server', models.ManyToManyField(to='monitor.server')),
            ],
        ),
    ]
