# Generated by Django 4.2 on 2024-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0043_remove_server_client_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='server',
            field=models.ManyToManyField(related_name='projects', to='monitor.server'),
        ),
    ]
