# Generated by Django 4.2 on 2024-05-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0044_alter_project_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='database',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.rds'),
        ),
    ]
