# Generated by Django 4.2 on 2024-05-29 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0047_serverstatus_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBalancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('arn', models.CharField(max_length=50)),
                ('elb_type', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoadBalancerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField()),
                ('state_code', models.CharField(max_length=50)),
                ('state_reason', models.CharField(max_length=50)),
                ('activity_data', models.JSONField(blank=True, null=True)),
                ('elb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.loadbalancer')),
            ],
            options={
                'verbose_name_plural': 'ELB status',
            },
        ),
        migrations.CreateModel(
            name='LoadBalancerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_datetime', models.DateTimeField()),
                ('register_date', models.DateField(db_index=True)),
                ('state_code', models.CharField(max_length=50)),
                ('state_reason', models.CharField(max_length=50)),
                ('metric_value', models.FloatField()),
                ('elb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.loadbalancer')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.servermetric')),
            ],
            options={
                'verbose_name_plural': 'ELB histories',
            },
        ),
    ]
