# Generated by Django 4.2 on 2024-05-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0050_alter_loadbalancer_arn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadbalancerhistory',
            options={'verbose_name_plural': 'Load balancer histories'},
        ),
        migrations.AlterModelOptions(
            name='loadbalancerstatus',
            options={'verbose_name_plural': 'Load balancer status'},
        ),
        migrations.AddField(
            model_name='servermetric',
            name='statistic',
            field=models.CharField(default='Average', max_length=50),
        ),
    ]
