# Generated by Django 4.2 on 2024-05-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0051_alter_loadbalancerhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadbalancerstatus',
            name='state_reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
