# Generated by Django 4.2 on 2024-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0054_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDSInstanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('core_count', models.IntegerField()),
                ('vcpu', models.IntegerField()),
                ('cpu_credits', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('network_performance', models.CharField(max_length=50)),
            ],
        ),
    ]
