# Generated by Django 4.2 on 2024-06-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0055_rdsinstanceclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rds',
            name='instance_class',
        ),
    ]
