# Generated by Django 4.2 on 2024-06-03 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0056_remove_rds_instance_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='instance_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.rdsinstanceclass'),
        ),
    ]
