# Generated by Django 4.2 on 2024-06-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0057_rds_instance_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdsstatus',
            name='allocated_storage',
            field=models.IntegerField(null=True),
        ),
    ]
