# Generated by Django 4.2 on 2024-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0058_rdsstatus_allocated_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadbalancerhistory',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadbalancerstatus',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rdshistory',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rdsstatus',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='to_exceed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='critical',
            field=models.BooleanField(default=False),
        ),
    ]
