# Generated by Django 4.2 on 2024-06-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0059_loadbalancerhistory_critical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gx',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
