# Generated by Django 4.2 on 2024-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0060_gx_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='unithistory',
            name='modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='license_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='license_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
