# Generated by Django 4.2 on 2024-07-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0061_unithistory_modified_alter_device_license_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadbalancerstatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
