# Generated by Django 4.2 on 2024-07-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0062_loadbalancerstatus_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='server',
            new_name='servers',
        ),
    ]
