# Generated by Django 4.2 on 2024-08-02 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0064_gxmetric_rombergdevice_alter_project_database_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rombergdevicehistory',
            options={'verbose_name_plural': 'Romberg device histories'},
        ),
        migrations.AlterModelOptions(
            name='rombergdevicestatus',
            options={'verbose_name_plural': 'Romberg device status'},
        ),
        migrations.AddField(
            model_name='rombergdevicehistory',
            name='last_alert',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rombergdevicehistory',
            name='register_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2024, 8, 2, 16, 5, 37, 161841)),
            preserve_default=False,
        ),
    ]
