# Generated by Django 4.2 on 2024-08-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0065_alter_rombergdevicehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rombergdevicestatus',
            name='last_alert',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
