# Generated by Django 4.2 on 2024-08-02 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0066_rombergdevicestatus_last_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gxrecord',
            old_name='average',
            new_name='avg_value',
        ),
        migrations.RenameField(
            model_name='gxrecord',
            old_name='register_datetime',
            new_name='generation_time',
        ),
        migrations.RenameField(
            model_name='gxrecord',
            old_name='maximum',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='gxrecord',
            old_name='minimum',
            new_name='min_value',
        ),
        migrations.RemoveField(
            model_name='gxmetric',
            name='statistic',
        ),
        migrations.AddField(
            model_name='gxrecord',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 18, 35, 2, 323064)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gxmetric',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
