# Generated by Django 4.2 on 2024-08-06 20:04

from django.db import migrations, models
import django.db.models.deletion
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0070_rename_generation_time_gxrecord_log_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gx',
            name='model',
            field=models.ForeignKey(default=monitor.models.GxModel.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='monitor.gxmodel'),
        ),
    ]
