# Generated by Django 4.2 on 2024-08-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0071_gx_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gxmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
